# Generated by Django 3.1.5 on 2021-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210305_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='risk_person',
            field=models.CharField(default='conservative', max_length=50),
        ),
    ]
