# Generated by Django 3.1.5 on 2021-03-06 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_risk_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
