# Generated by Django 3.1.5 on 2021-03-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='risk_person',
            field=models.CharField(choices=[('CS', 'Conservador'), ('MD', 'Moderado'), ('BD', 'Arrojado')], default='CS', max_length=2),
        ),
    ]
