# Generated by Django 3.1.5 on 2021-03-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210305_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.investor'),
        ),
    ]
